export const motivations: string[] = [
  "I code because I can't dance, and trust me, you don't want to see that.",
  "If at first you don't succeed, just remember: even the Titanic was unsinkable once.",
  "My code might not be perfect, but it's a masterpiece of controlled chaos.",
  "I turn coffee into code - because who needs sleep when you've got deadlines?",
  "Debugging is like being the detective in a crime movie where you're also the murderer.",
  "Why settle for 'works' when you can aim for 'works, but in a weird way'? ",
  "In a world full of 'normal' code, dare to be an exception handler.",
  "Remember, if Plan A fails, there are 25 more letters in the alphabet. Or you can just start over with A again.",
  "My portfolio: where dreams meet reality, and then reality laughs.",
  "I'm not lazy, I'm on energy-saving mode - perfect for sustainable coding.",
  "When you want to give up, remember why you started. When you want to slow down, remember why you can't. And when you want to stop, remember why you must.",
  "I write code like I brush my teeth - haphazardly and with too much toothpaste.",
  "My programs are like my socks: they might match now, but give it a day.",
  "Ever notice how 'debugging' sounds like 'de-bugging'? Coincidence? I think not.",
  "I believe in the power of positive procrastination: if you wait long enough, the problem might just solve itself.",
  "My coding philosophy: If it runs on the first try, it's probably not doing anything.",
  "Why use logic when you can confuse the universe with sheer randomness?",
  "I code so my cat can have a more comfortable life... by sitting on my keyboard.",
  "In my code, 'efficiency' is just a word I use to sound smart at parties.",
  "I'm the Michelangelo of spaghetti code; it's not a mess, it's art.",
  "My goal is to make software that's as intuitive as a Rubik's Cube in a dark room.",
  "Remember, if your code doesn't make you question your life choices, you're not trying hard enough.",
  "I treat deadlines like I treat my diet - something to acknowledge from afar.",
  "My code might not be 'best practice', but it's certainly 'best surprise'.",
  "Who needs comments when you can guess what the code does?",
  "I'm not saying my code is bad, but if it were a movie, it'd be a mystery thriller where even the writer doesn't know the ending.",
  "Your code is so bad, it makes Windows Vista look like a stable genius.",
  "If your coding is an art, then Jackson Pollock must be your muse.",
  "You call that 'optimization'? My grandma's knitting patterns are more efficient.",
  "Your commit history looks like a crime scene - and you're the only suspect.",
  "If spaghetti code had a poster child, it would be waving back at you from your mirror.",
  "Your debugging skills are so legendary, they're the reason we have the term 'nightmare'.",
  "Is that a coding project or did you just throw every keyword into a blender?",
  "Your software is so user-unfriendly, it makes tax forms look like children's books.",
  "I've seen better code structure in a bowl of alphabet soup.",
  "Your version control is like your personal life - a chaotic mess no one wants to sort out.",
  "If your code was a car, it would be a lemon, but without the charm of being vintage.",
  "You think you're debugging, but really, you're just adding more bugs for future you to find.",
  "Your approach to coding is like trying to fix a watch with a sledgehammer.",
  "If your code was food, it would be the burnt toast of the programming world.",
  "You're the reason why 'Ctrl+Z' was invented - to undo the horrors you unleash.",
];
