const myData = {
  name: "Ruru",
  iam: [
    "Web Development.",
    "UI/UX Design.",
    "Cloud Computing.",
    "Web Security.",
    "Frontend Frameworks.",
    "Backend Architectures.",
    "API Design.",
    "Content Management Systems.",
    "Web Performance Optimization.",
    "Responsive Design.",
  ],
  //   you can file icons here https://simpleicons.org/
  skillslugs: [
    "typescript",
    "javascript",
    "react",
    "html5",
    "css3",
    "nodedotjs",
    "express",
    "nextdotjs",
    "prisma",
    "amazonaws",
    "postgresql",
    "firebase",
    "nginx",
    "vercel",
    "docker",
    "git",
    "github",
    "gitlab",
    "visualstudiocode",
    "figma",
    "postman",
    "apachekafka",
    "redis",
    "linux",
    "appwrite",
    "grafana",
  ],
};

export default myData;
